kat_kem.rsp: kat
	./run

kat: Makefile ../common/kat_kem_vectors.c nist/rng.c nist/rng.h ../common/core/controlbits.c ../common/core/encrypt.c gf.c ../common/core/operations.c ../common/core/pk_gen.c ../common/core/root.c ../common/core/sk_gen.c util.c ../common/core/controlbits.h ../common/core/encrypt.h ../common/core/gf.h ../common/core/pk_gen.h ../common/core/root.h ../common/core/sk_gen.h ../common/core/randombytes.h ../common/core/crypto_hash.h ../common/core/int32_sort.h ../common/core/uint64_sort.h
	./build
